## Data Prep for the 5 datasets for Markers

In [2]:
import csv
import pandas as pd

In [13]:
df_golf = pd.read_csv('Golf_Courses_in_Austin.csv')

In [14]:
df_golf = df_golf[['Name','Location']]

In [15]:
df_golf

,Name,Location
0,Lions Municipal Golf Course,"2901 Enfield Road\nAustin, Texas\n(30.29160354..."
1,Joe Balander Short Course,"5400 Jimmy Clay Drive\nAustin, Texas\n(30.1881..."
2,Morris Williams Golf Course,"3851 Manor Road\nAustin, Texas\n(30.2900767931..."
3,Roy Kizer Golf Course,"5400 Jimmy Clay Drive\nAustin, Texas\n(30.1881..."
4,Hancock Golf Course,"811 East 41st Street\nAustin, Texas\n(30.29983..."
5,Jimmy Clay Golf Course,"5400 Jimmy Clay Drive\nAustin, Texas\n(30.1881..."

In [16]:
df_golf.to_csv('golfdata.csv', index=False)

In [17]:
df_golf = pd.read_csv('golfdata.csv') 
df_golf

                          Name        Lat       Long
0  Lions Municipal Golf Course  30.291604 -97.774277
1    Joe Balander Short Course  30.188193 -97.732533
2  Morris Williams Golf Course  30.290077 -97.694168
3        Roy Kizer Golf Course  30.188193 -97.732533
4          Hancock Golf Course  30.299834 -97.722640
5       Jimmy Clay Golf Course  30.188193 -97.732533

In [65]:
df_golf['Category'] = 'GolfCourse'
df_golf.head()

                          Name        Lat       Long    Category
0  Lions Municipal Golf Course  30.291604 -97.774277  GolfCourse
1    Joe Balander Short Course  30.188193 -97.732533  GolfCourse
2  Morris Williams Golf Course  30.290077 -97.694168  GolfCourse
3        Roy Kizer Golf Course  30.188193 -97.732533  GolfCourse
4          Hancock Golf Course  30.299834 -97.722640  GolfCourse

In [18]:
df_labs = pd.read_csv('Public_Computer_Labs.csv') 
df_labs

,Name,Location,Address,City,State,Zipcode,Phone number,Hours,Website,Number of Computers,New Georeferenced Column
0,ARCH,500 E. 7th St. 78701,500 E. 7th St.,Austin,TX,78701,(512) 978-9920,M-F: 6:30a-11a; 12p-3:30p,http://frontsteps.org/what-we-do/arch/,NaN,POINT (-97.737726 30.267652)
1,Howson Library,2500 Exposition Blvd. 78703,2500 Exposition Blvd.,Austin,TX,78703,(512) 974-8800,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/howson-branch,5.0,POINT (-97.767313 30.298139)
2,Old Quarry Library,7051 Village Center Dr. 78731,7051 Village Center Dr.,Austin,TX,78731,(512) 974-8860,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/old-quarry-branch,6.0,POINT (-97.755751 30.353257)
3,Spicewood Springs Library,8637 Spicewood Springs Rd. 78759,8637 Spicewood Springs Rd.,Austin,TX,78759,(512) 974-3800,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm,",https://library.austintexas.gov/spicewood-spri...,20.0,POINT (-97.772786 30.433288)
4,Windsor Park Library,5833 Westminster Drive 78723,5833 Westminster Drive,Austin,TX,78723,(512) 974-9840,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/windsor-park-b...,24.0,POINT (-97.690559 30.311258)
5,Carver Library,1161 Angelina St. 78702,1161 Angelina St.,Austin,TX,78702,(512) 974-1010,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/carver-branch,28.0,POINT (-97.724523 30.26995)
6,Little Walnut Creek Library,835 Rundberg Lane 78758,835 Rundberg Lane,Austin,TX,78758,(512) 974-9860,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm, Su...",https://library.austintexas.gov/little-walnut-...,24.0,POINT (-97.698231 30.363634)
7,North Village Library,2505 Steck Ave. 78757,2505 Steck Ave.,Austin,TX,78757,(512) 974-9960,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm, Su...",https://library.austintexas.gov/north-village-...,21.0,POINT (-97.729717 30.362014)
8,Southeast Library,5803 Nuckols Crossing Road 78744,5803 Nuckols Crossing Road,Austin,TX,78744,(512) 974-8840,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/southeast-branch,23.0,POINT (-97.742224 30.187926)
9,Central Library,710 W. César Chávez St. 78701,710 W. César Chávez St.,Austin,TX,78701,(512) 974-7400,"M-Th: 10am-9pm, F, Sat: 10am-6pm, Sun: 12pm-6pm",https://library.austintexas.gov/central-library,155.0,POINT (-97.751941 30.265509)
10,Twin Oaks Library,1800 S. Fifth St. 78704,1800 S. Fifth St.,Austin,TX,78704,(512) 974-9980,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/twin-oaks-branch,29.0,POINT (-97.761726 30.248884)
11,Ruiz Library,1600 Grove Blvd. 78741,1600 Grove Blvd.,Austin,TX,78741,(512) 974-7500,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm, Su...",https://library.austintexas.gov/ruiz-branch,41.0,POINT (-97.706314 30.230228)
12,Manchaca Road Library,5500 Manchaca Rd. 78745,5500 Manchaca Rd.,Austin,TX,78745,(512) 974-8700,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm, Su...",https://library.austintexas.gov/manchaca-road-...,19.0,POINT (-97.796899 30.216327)
13,Cepeda Library,651 N. Pleasant Valley Rd. 78702,651 N. Pleasant Valley Rd.,Austin,TX,78702,(512) 974-7372,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/cepeda-branch,11.0,POINT (-97.709632 30.259785)
14,University Hills Library,4721 Loyola Lane 78723,4721 Loyola Lane,Austin,TX,78723,(512) 974-9940,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/university-hil...,NaN,POINT (-97.666211 30.308952)
15,Terrazas Library,1105 E. César Chávez St. 78702,1105 E. César Chávez St.,Austin,TX,78702,(512) 974-3625,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/terrazas-branch,23.0,POINT (-97.733214 30.260114)
16,Pleasant Hill Library,211 E. William Cannon Drive 78745,211 E. William Cannon Drive,Austin,TX,78745,(512) 974-3940,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/pleasant-hill-...,NaN,POINT (-97.777026 30.192555)
17,Milwood Library,12500 Amherst Dr. 78727,12500 Amherst Dr.,Austin,TX,78727,(512) 974-9880,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/milwood-branch,6.0,POINT (-97.714651 30.423153)
18,Willie Mae Kirk Library,3101 Oak Springs Drive 78702,3101 Oak Springs Drive,Austin,TX,78702,(512) 974-9920,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-5pm",https://library.austintexas.gov/willie-mae-kir...,20.0,POINT (-97.69999 30.273232)
19,Dewitty Center,2209 Rosewood Ave. 78702,2209 Rosewood Ave.,Austin,TX,78702,(512) 236-8225,M-F: 9-4,http://www.austintexas.gov/contact-information...,NaN,POINT (-97.7159 30.27021)
20,St. John Library,7500 Blessing Ave. 78752,7500 Blessing Ave.,Austin,TX,78752,(512) 974-7570,"M-Th: 10am-9pm, F: 10am-6pm, Sat: 10am-4pm",https://library.austintexas.gov/st-john-branch,32.0,POINT (-97.693032 30.331949)

In [19]:
df_labs = df_labs[['Name','New Georeferenced Column']]
df_labs

                           Name      New Georeferenced Column
0                          ARCH  POINT (-97.737726 30.267652)
1                Howson Library  POINT (-97.767313 30.298139)
2            Old Quarry Library  POINT (-97.755751 30.353257)
3     Spicewood Springs Library  POINT (-97.772786 30.433288)
4          Windsor Park Library  POINT (-97.690559 30.311258)
5                Carver Library   POINT (-97.724523 30.26995)
6   Little Walnut Creek Library  POINT (-97.698231 30.363634)
7         North Village Library  POINT (-97.729717 30.362014)
8             Southeast Library  POINT (-97.742224 30.187926)
9               Central Library  POINT (-97.751941 30.265509)
10            Twin Oaks Library  POINT (-97.761726 30.248884)
11                 Ruiz Library  POINT (-97.706314 30.230228)
12        Manchaca Road Library  POINT (-97.796899 30.216327)
13               Cepeda Library  POINT (-97.709632 30.259785)
14     University Hills Library  POINT (-97.666211 30.308952)
15             Terrazas Library  POINT (-97.733214 30.260114)
16        Pleasant Hill Library  POINT (-97.777026 30.192555)
17              Milwood Library  POINT (-97.714651 30.423153)
18      Willie Mae Kirk Library   POINT (-97.69999 30.273232)
19               Dewitty Center     POINT (-97.7159 30.27021)
20             St. John Library  POINT (-97.693032 30.331949)

In [20]:
df_labs['Lat'] = df_labs['New Georeferenced Column'].str[7:]
df_labs

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Name,New Georeferenced Column,Lat
0,ARCH,POINT (-97.737726 30.267652),-97.737726 30.267652)
1,Howson Library,POINT (-97.767313 30.298139),-97.767313 30.298139)
2,Old Quarry Library,POINT (-97.755751 30.353257),-97.755751 30.353257)
3,Spicewood Springs Library,POINT (-97.772786 30.433288),-97.772786 30.433288)
4,Windsor Park Library,POINT (-97.690559 30.311258),-97.690559 30.311258)
5,Carver Library,POINT (-97.724523 30.26995),-97.724523 30.26995)
6,Little Walnut Creek Library,POINT (-97.698231 30.363634),-97.698231 30.363634)
7,North Village Library,POINT (-97.729717 30.362014),-97.729717 30.362014)
8,Southeast Library,POINT (-97.742224 30.187926),-97.742224 30.187926)
9,Central Library,POINT (-97.751941 30.265509),-97.751941 30.265509)
10,Twin Oaks Library,POINT (-97.761726 30.248884),-97.761726 30.248884)
11,Ruiz Library,POINT (-97.706314 30.230228),-97.706314 30.230228)
12,Manchaca Road Library,POINT (-97.796899 30.216327),-97.796899 30.216327)
13,Cepeda Library,POINT (-97.709632 30.259785),-97.709632 30.259785)
14,University Hills Library,POINT (-97.666211 30.308952),-97.666211 30.308952)
15,Terrazas Library,POINT (-97.733214 30.260114),-97.733214 30.260114)
16,Pleasant Hill Library,POINT (-97.777026 30.192555),-97.777026 30.192555)
17,Milwood Library,POINT (-97.714651 30.423153),-97.714651 30.423153)
18,Willie Mae Kirk Library,POINT (-97.69999 30.273232),-97.69999 30.273232)
19,Dewitty Center,POINT (-97.7159 30.27021),-97.7159 30.27021)
20,St. John Library,POINT (-97.693032 30.331949),-97.693032 30.331949)

In [23]:
new = df_labs["Lat"].str.split(" ", n = 1, expand = True)

In [24]:
new

             0           1
0   -97.737726  30.267652)
1   -97.767313  30.298139)
2   -97.755751  30.353257)
3   -97.772786  30.433288)
4   -97.690559  30.311258)
5   -97.724523   30.26995)
6   -97.698231  30.363634)
7   -97.729717  30.362014)
8   -97.742224  30.187926)
9   -97.751941  30.265509)
10  -97.761726  30.248884)
11  -97.706314  30.230228)
12  -97.796899  30.216327)
13  -97.709632  30.259785)
14  -97.666211  30.308952)
15  -97.733214  30.260114)
16  -97.777026  30.192555)
17  -97.714651  30.423153)
18   -97.69999  30.273232)
19    -97.7159   30.27021)
20  -97.693032  30.331949)

In [26]:
df_labs['Long'] = new[0]
df_labs['Lat'] = new[1]
df_labs

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Name,New Georeferenced Column,Lat,Long
0,ARCH,POINT (-97.737726 30.267652),30.267652),-97.737726
1,Howson Library,POINT (-97.767313 30.298139),30.298139),-97.767313
2,Old Quarry Library,POINT (-97.755751 30.353257),30.353257),-97.755751
3,Spicewood Springs Library,POINT (-97.772786 30.433288),30.433288),-97.772786
4,Windsor Park Library,POINT (-97.690559 30.311258),30.311258),-97.690559
5,Carver Library,POINT (-97.724523 30.26995),30.26995),-97.724523
6,Little Walnut Creek Library,POINT (-97.698231 30.363634),30.363634),-97.698231
7,North Village Library,POINT (-97.729717 30.362014),30.362014),-97.729717
8,Southeast Library,POINT (-97.742224 30.187926),30.187926),-97.742224
9,Central Library,POINT (-97.751941 30.265509),30.265509),-97.751941
10,Twin Oaks Library,POINT (-97.761726 30.248884),30.248884),-97.761726
11,Ruiz Library,POINT (-97.706314 30.230228),30.230228),-97.706314
12,Manchaca Road Library,POINT (-97.796899 30.216327),30.216327),-97.796899
13,Cepeda Library,POINT (-97.709632 30.259785),30.259785),-97.709632
14,University Hills Library,POINT (-97.666211 30.308952),30.308952),-97.666211
15,Terrazas Library,POINT (-97.733214 30.260114),30.260114),-97.733214
16,Pleasant Hill Library,POINT (-97.777026 30.192555),30.192555),-97.777026
17,Milwood Library,POINT (-97.714651 30.423153),30.423153),-97.714651
18,Willie Mae Kirk Library,POINT (-97.69999 30.273232),30.273232),-97.69999
19,Dewitty Center,POINT (-97.7159 30.27021),30.27021),-97.7159
20,St. John Library,POINT (-97.693032 30.331949),30.331949),-97.693032

In [27]:
del df_labs['New Georeferenced Column']
df_labs

                           Name         Lat        Long
0                          ARCH  30.267652)  -97.737726
1                Howson Library  30.298139)  -97.767313
2            Old Quarry Library  30.353257)  -97.755751
3     Spicewood Springs Library  30.433288)  -97.772786
4          Windsor Park Library  30.311258)  -97.690559
5                Carver Library   30.26995)  -97.724523
6   Little Walnut Creek Library  30.363634)  -97.698231
7         North Village Library  30.362014)  -97.729717
8             Southeast Library  30.187926)  -97.742224
9               Central Library  30.265509)  -97.751941
10            Twin Oaks Library  30.248884)  -97.761726
11                 Ruiz Library  30.230228)  -97.706314
12        Manchaca Road Library  30.216327)  -97.796899
13               Cepeda Library  30.259785)  -97.709632
14     University Hills Library  30.308952)  -97.666211
15             Terrazas Library  30.260114)  -97.733214
16        Pleasant Hill Library  30.192555)  -97.777026
17              Milwood Library  30.423153)  -97.714651
18      Willie Mae Kirk Library  30.273232)   -97.69999
19               Dewitty Center   30.27021)    -97.7159
20             St. John Library  30.331949)  -97.693032

In [28]:
df_labs['Lat'] = df_labs['Lat'].str[:-1]
df_labs

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                           Name        Lat        Long
0                          ARCH  30.267652  -97.737726
1                Howson Library  30.298139  -97.767313
2            Old Quarry Library  30.353257  -97.755751
3     Spicewood Springs Library  30.433288  -97.772786
4          Windsor Park Library  30.311258  -97.690559
5                Carver Library   30.26995  -97.724523
6   Little Walnut Creek Library  30.363634  -97.698231
7         North Village Library  30.362014  -97.729717
8             Southeast Library  30.187926  -97.742224
9               Central Library  30.265509  -97.751941
10            Twin Oaks Library  30.248884  -97.761726
11                 Ruiz Library  30.230228  -97.706314
12        Manchaca Road Library  30.216327  -97.796899
13               Cepeda Library  30.259785  -97.709632
14     University Hills Library  30.308952  -97.666211
15             Terrazas Library  30.260114  -97.733214
16        Pleasant Hill Library  30.192555  -97.777026
17              Milwood Library  30.423153  -97.714651
18      Willie Mae Kirk Library  30.273232   -97.69999
19               Dewitty Center   30.27021    -97.7159
20             St. John Library  30.331949  -97.693032

In [64]:
df_labs['Category'] = 'ComputerLab'
df_labs.head()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                        Name        Lat        Long     Category
0                       ARCH  30.267652  -97.737726  ComputerLab
1             Howson Library  30.298139  -97.767313  ComputerLab
2         Old Quarry Library  30.353257  -97.755751  ComputerLab
3  Spicewood Springs Library  30.433288  -97.772786  ComputerLab
4       Windsor Park Library  30.311258  -97.690559  ComputerLab

In [37]:
df_shoot = pd.read_csv('Officer_Involved_Shootings_2008-17_Incidents.csv') 
df_shoot

,Case #,Date,Day of Week,Time,Premise Category,Less Lethal Force used by APD prior to shooting?,Subject Weapon,Number of Officer Shooters,Call Type Categories,# Officers Present When Shots Fired,# Hits,Location 1
0,15-0381788\n15-5005471\n15-5006662,02/08/2015,Sun,12:09 PM,Yard/Courtyard,No,rifle,1,shots fired,26,1.0,"8206 Pax Dr\n(30.244609, -97.888612)"
1,14-3320160\n14-5052475,11/28/2014,Fri,2:22 AM,Street,No,rifle,1,shots fired,10,1.0,"715 E 8th St\n(48.192789, -114.299949)"
2,13-5048070\n13-5048073\n13-2911294,10/18/2013,Fri,3:20 PM,Yard/Courtyard,No,rifle,3,shots fired,5,1.0,"1609 Cripple Creek Dr\n(30.379773, -97.704626)"
3,17-0531372\n17-5015929\n17-5007713,02/22/2017,Wed,6:16 PM,wooded area,no,knife,1,other - nature unknown,1,2.0,"7600 MANCHACA RD\n(30.1955, -97.810196)"
4,17-1270282\n17-5018795\n17-5026492\n17-1270300,05/07/2017,Sun,2:39 AM,street,no,handgun,1,shots fired,8,3.0,"600 TRINITY ST\n(29.881245, -97.667536)"
5,09-0431751,02/12/2009,Thu,5:51 PM,Parking Lot,No,"gun, vehicle",1,warrant,4,2.0,"9218 Balcones Club Dr\n(30.443284, -97.787553)"
6,11-5038917\n11-2271207,08/15/2011,Mon,4:50 PM,Street,No,gun,2,robbery,3,0.0,"3630 S Congress Ave\n(26.489341, -80.089825)"
7,12-5047326\n12-2940313,10/20/2012,Sat,2:10 AM,Street,No,vehicle,1,disturbance,3,0.0,"300 block E 6th St\n(38.848634, -91.944226)"
8,13-5019982\n13-1280390,05/08/2013,Wed,7:51 AM,Street,No,none,1,traffic stop,1,0.0,"3300 E 12th St\n(40.178357, -85.348554)"
9,15-0230201\n15-5003040\n15-5003476,01/23/2015,Fri,3:45 AM,Parking Lot,No,gun,1,domestic disturbance,4,2.0,"120 W Slaughter Ln\n(30.167208, -97.788916)"
10,11-3390300,12/05/2011,Mon,6:53 AM,Street,No,vehicle,2,stolen vehicle,10,3.0,"3708 Aspen Creek Pkwy\n(30.181796, -97.856066)"
11,15-1860670\n15-5029092\n15-5030645,07/05/2015,Sun,4:14 AM,Residence,Yes - Taser,pellet gun,3,suicidal subject,3,6.0,"10607 Golden Quail Dr\n(30.379781, -97.70205)"
12,14-5003813\n14-0250881,01/25/2014,Sat,1:42 PM,Parking Lot,No,vehicle,1,other - flagged down by victim of an LTS,1,0.0,"9400 N Lamar Blvd\n(30.363177, -97.696992)"
13,10-2740401\n10-2741075,10/01/2010,Fri,5:53 AM,Business,No,gun,1,burglar alarm,2,4.0,"801 E William Cannon Dr\n(30.19096, -97.771937)"
14,10-5055642\n10-2680066,09/25/2010,Sat,4:26 AM,Street,No,gun,1,domestic disturbance,30,1.0,"7800 E Ben White Blvd WB\n(30.219623, -97.689696)"
15,16-2900369\n16-5046503\n16-5042860,10/16/2016,Sun,3:54 AM,Residence,No,air pistol (BB gun),2,check welfare,5,5.0,"744 W William Cannon Dr\n(30.197953, -97.789496)"
16,17-1220770\n17-5018080\n17-5041807,05/02/2017,Tue,11:17 AM,street,no,handgun,1,disturbance,5,2.0,"11300 block LONG WINTER DR\n(37.49396, -92.294..."
17,11-5052201\n11-3090370,11/05/2011,Sat,3:10 AM,Parking Lot,Yes - Taser,none (radio face plate),1,disturbance,2,0.0,"810 E Slaughter Ln\n(30.159946, -97.77643)"
18,11-5060110 11-3621220,12/28/2011,Wed,5:19 PM,Parking Lot,No,vehicle,1,other - narcotics,4,0.0,"7800 N IH 35 Svrd SB\n(29.56345, -98.340468)"
19,15-1860826\n15-5029094\n15-5030656,07/05/2015,Sun,4:54 AM,Business,No,rifle,1,shots fired,3,10.0,"700 San Jacinto Blvd\n(30.269158, -97.739649)"
20,17-972006\n17-5014510,04/07/2017,Fri,10:12 PM,residence,no,rifle,4,disturbance,9,9.0,"6321 PARLIAMENT DR\n(30.28687, -97.658896)"
21,10-5058733\n10-5058741\n10-5058742\n10-3060261,11/02/2010,Tue,05:17 / 06:10,Residence / Parking Lot,No,gun,2,disturbance,5,4.0,12320 Tomanet Trl / 12331 N Mopac Expy Svrd NB...
22,15-1440098\n15-5022158,05/24/2015,Sun,1:14 AM,Yard/Courtyard,No,gun,2,suspicious person,3,3.0,"6409 Springdale Rd\n(30.307201, -97.669664)"
23,17-5005154\n17-370047,02/06/2017,Mon,12:41 AM,street,no,vehicle,1,traffic stop,3,0.0,"1100 Marks Circle\n(30.268608, -97.691009)"
24,11-5028251\n11-1502313,05/30/2011,Mon,11:07 PM,Street,No,vehicle,1,suspicious person,2,4.0,"800 Block E 8th St\n(40.868762, -97.583783)"
25,09-5072203\n09-3620161,12/28/2009,Mon,2:54 AM,Residence,No,gun,2,domestic disturbance,3,1.0,"11815 Johnny Weismuller Ln\n(30.151215, -97.84..."
26,16-1131869\n16-5031156\n16-5016874,04/22/2016,Fri,10:20 PM,Parking Lot,No,knife,1,disturbance,1,1.0,"6600 S MoPac Expy Svrd SB\n(30.221231, -97.836..."
27,17-5049741\n17-3490320,12/15/2017,Fri,6:49 AM,residence,no,knife,1,other - stabbing,1,1.0,"5007 Lynnwood St\n(30.322115, -97.740477)"
28,13-5009062\n13-0600435,03/01/2013,Fri,7:32 AM,Residence,No,gun,1,shots fired,1,2.0,"10617 Lanshire Dr\n(30.384132, -97.708018)"
29,17-140100\n17-5001846\n17-5020338,01/14/2017,Sat,2:03 AM,church,no,rifle and shotgun,1,disturbance,4,5.0,"11512 OLSON DR\n(30.445259, -97.805086)"
30,10-5068185\n10-3572205,12/23/2010,Thu,10:53 PM,Street,Yes - Taser and Weaponless,knife,1,traffic stop,2,1.0,"13006 Campos Dr\n(30.438023, -97.740493)"
31,15-1450142\n15-5022316\n15-5022877,05/25/2015,Mon,6:13 AM,Yard/Courtyard,Yes - impact weapon,gun,1,suicidal subject,10,3.0,"6505 Shirley Ave\n(30.33259, -97.720879)"
32,13-5052096\n13-3141499,11/10/2013,Sun,9:17 PM,Yard/Courtyard,No,gun,2,check welfare,9,1.0,"2900 Cole St\n(30.2877, -97.725141)"
33,09-5052963\n09-2280484,08/16/2009,Sun,3:06 AM,Parking Lot,No,vehicle,2,traffic stop,3,4.0,"1515 Wickersham Ln\n(30.235461, -97.718944)"
34,12-5016942\n12-0961610,04/05/2012,Thu,6:40 PM,Yard/Courtyard,Yes - Taser and Weaponless,mic cord,1,traffic stop,1,3.0,"5200 Block Overbrook Dr\n(30.298349, -97.684711)"
35,16-2581947\n16-5040418\n16-5038102,09/15/2016,Thu,12:02 AM,Parking Lot,Yes - Taser,handgun,2,suspicious person,4,5.0,"4201 Monterey Oaks Blvd\n(30.228925, -97.83392)"
36,16-940866\n16-941306\n16-5013826\n16-5017173,04/03/2016,Sun,11:01 AM,Parking Lot,No,gun,1,disturbance,1,3.0,"508 West Ave\n(30.298878, -82.978832)"
37,13-5021565\n13-1370254,05/17/2013,Fri,3:27 AM,Yard/Courtyard,No,gun,1,shots fired,3,0.0,"6855 E US 290 Hwy SVRD EB\n(30.321071, -97.687..."
38,13-5039952\n13-2430035,08/31/2013,Sat,12:13 AM,Parking Lot,No,vehicle,1,burglar alarm,1,5.0,"9416 Neils Thompson Dr\n(30.382402, -97.733069)"
39,13-5002063\n13-0141039,01/14/2013,Mon,3:30 PM,Parking Lot,No,gun,2,robbery,2,0.0,"7112 Ed Bluestein Blvd SVRD SB\n(30.312738, -9..."
40,15-1922009\n15-5030362,07/12/2015,Sun,12:51 PM,Yard/Courtyard,No,gun,1,suspicious person,2,2.0,"9400 Claxton Dr\n(30.246406, -97.910421)"
41,09-5053921\n09-1310302,05/11/2009,Mon,5:07 AM,Parking Lot,No,gun,1,other - robbery suspect vehicle,3,3.0,"6409 Springdale Rd\n(30.307201, -97.669664)"
42,16-1050267\n16-5015495,04/14/2016,Thu,5:56 AM,Residence,No,rifle,1,warrant,8,0.0,"1002 Morrow St\n(30.345194, -97.717559)"
43,12-5005552\n12-0341696,02/03/2012,Fri,9:33 PM,Parking Lot,No,gun,1,check welfare,16,1.0,"7201 Wood Hollow Dr\n(30.355057, -97.752106)"
44,14-2511591,09/08/2014,Mon,7:38 PM,Residence,No,gun,3,warrant,3,2.0,"13712 Maye Pl\n(30.426237, -97.673119)"
45,16-801294\n16-5011754,03/20/2016,Sun,11:07 PM,Parking Lot,no,knife,1,other - aggravated assault,1,1.0,"9811 N IH 35 SVRD NB\n(30.362494, -97.684934)"
46,12-5043966\n12-2691696,09/25/2012,Tue,8:39 PM,Parking Lot,No,vehicle,1,stolen vehicle,2,1.0,"2915 S IH 35 Svrd NB\n(30.227091, -97.74466)"
47,08-5059600\n08-3110300,11/06/2008,Thu,3:56 AM,Parking Lot,No,gun,1,disturbance,3,2.0,"6603 Berkman Dr\n(30.319315, -97.689358)"
48,13-5017606\n13-1131720,04/23/2013,Tue,8:40 PM,Yard/Courtyard,No,rifle,4,suicidal subject,4,7.0,"706 Valdez St\n(30.234584, -97.691949)"
49,17-5049986\n17-3510568,12/17/2017,Sun,10:42 AM,residence,no,knife,1,disturbance,1,NaN,"4022 Greenhill Place\n(30.379441, -97.751594)"
50,11-5023381\n11-1290071,05/09/2011,Mon,1:03 AM,Yard/Courtyard,No,gun,1,shots fired,2,3.0,"1919 Burton Dr\n(30.233907, -97.731631)"
51,14-5012166\n14-0770816,03/18/2014,Tue,12:24 PM,Yard/Courtyard,No,air pistol (BB gun),1,domestic disturbance,1,2.0,"6301 Berkman Dr\n(30.316889, -97.690853)"
52,09-5006129\n09-0302652,01/30/2009,Fri,10:46 PM,Business,No,gun,1,burglar alarm,8,0.0,"4714 S Congress Ave\n(30.214181, -97.769479)"
53,16-2492260\n16-5036999\n16-5036744,09/05/2016,Mon,9:03 AM,Parking Lot,Yes - impact weapon,rifle,2,domestic disturbance,14,4.0,"12501 Tech Ridge Blvd\n(30.398698, -97.661704)"
54,16-390552\n16-5007698\n16-6005558\n,02/08/2016,Mon,10:26 AM,residence,no,none,1,suspicious person,1,2.0,"12000 block Natures Bnd\n(30.391489, -97.667084)"

In [38]:
df_shoot = df_shoot[['Call Type Categories','Location 1']]
df_shoot

,Call Type Categories,Location 1
0,shots fired,"8206 Pax Dr\n(30.244609, -97.888612)"
1,shots fired,"715 E 8th St\n(48.192789, -114.299949)"
2,shots fired,"1609 Cripple Creek Dr\n(30.379773, -97.704626)"
3,other - nature unknown,"7600 MANCHACA RD\n(30.1955, -97.810196)"
4,shots fired,"600 TRINITY ST\n(29.881245, -97.667536)"
5,warrant,"9218 Balcones Club Dr\n(30.443284, -97.787553)"
6,robbery,"3630 S Congress Ave\n(26.489341, -80.089825)"
7,disturbance,"300 block E 6th St\n(38.848634, -91.944226)"
8,traffic stop,"3300 E 12th St\n(40.178357, -85.348554)"
9,domestic disturbance,"120 W Slaughter Ln\n(30.167208, -97.788916)"
10,stolen vehicle,"3708 Aspen Creek Pkwy\n(30.181796, -97.856066)"
11,suicidal subject,"10607 Golden Quail Dr\n(30.379781, -97.70205)"
12,other - flagged down by victim of an LTS,"9400 N Lamar Blvd\n(30.363177, -97.696992)"
13,burglar alarm,"801 E William Cannon Dr\n(30.19096, -97.771937)"
14,domestic disturbance,"7800 E Ben White Blvd WB\n(30.219623, -97.689696)"
15,check welfare,"744 W William Cannon Dr\n(30.197953, -97.789496)"
16,disturbance,"11300 block LONG WINTER DR\n(37.49396, -92.294..."
17,disturbance,"810 E Slaughter Ln\n(30.159946, -97.77643)"
18,other - narcotics,"7800 N IH 35 Svrd SB\n(29.56345, -98.340468)"
19,shots fired,"700 San Jacinto Blvd\n(30.269158, -97.739649)"
20,disturbance,"6321 PARLIAMENT DR\n(30.28687, -97.658896)"
21,disturbance,12320 Tomanet Trl / 12331 N Mopac Expy Svrd NB...
22,suspicious person,"6409 Springdale Rd\n(30.307201, -97.669664)"
23,traffic stop,"1100 Marks Circle\n(30.268608, -97.691009)"
24,suspicious person,"800 Block E 8th St\n(40.868762, -97.583783)"
25,domestic disturbance,"11815 Johnny Weismuller Ln\n(30.151215, -97.84..."
26,disturbance,"6600 S MoPac Expy Svrd SB\n(30.221231, -97.836..."
27,other - stabbing,"5007 Lynnwood St\n(30.322115, -97.740477)"
28,shots fired,"10617 Lanshire Dr\n(30.384132, -97.708018)"
29,disturbance,"11512 OLSON DR\n(30.445259, -97.805086)"
30,traffic stop,"13006 Campos Dr\n(30.438023, -97.740493)"
31,suicidal subject,"6505 Shirley Ave\n(30.33259, -97.720879)"
32,check welfare,"2900 Cole St\n(30.2877, -97.725141)"
33,traffic stop,"1515 Wickersham Ln\n(30.235461, -97.718944)"
34,traffic stop,"5200 Block Overbrook Dr\n(30.298349, -97.684711)"
35,suspicious person,"4201 Monterey Oaks Blvd\n(30.228925, -97.83392)"
36,disturbance,"508 West Ave\n(30.298878, -82.978832)"
37,shots fired,"6855 E US 290 Hwy SVRD EB\n(30.321071, -97.687..."
38,burglar alarm,"9416 Neils Thompson Dr\n(30.382402, -97.733069)"
39,robbery,"7112 Ed Bluestein Blvd SVRD SB\n(30.312738, -9..."
40,suspicious person,"9400 Claxton Dr\n(30.246406, -97.910421)"
41,other - robbery suspect vehicle,"6409 Springdale Rd\n(30.307201, -97.669664)"
42,warrant,"1002 Morrow St\n(30.345194, -97.717559)"
43,check welfare,"7201 Wood Hollow Dr\n(30.355057, -97.752106)"
44,warrant,"13712 Maye Pl\n(30.426237, -97.673119)"
45,other - aggravated assault,"9811 N IH 35 SVRD NB\n(30.362494, -97.684934)"
46,stolen vehicle,"2915 S IH 35 Svrd NB\n(30.227091, -97.74466)"
47,disturbance,"6603 Berkman Dr\n(30.319315, -97.689358)"
48,suicidal subject,"706 Valdez St\n(30.234584, -97.691949)"
49,disturbance,"4022 Greenhill Place\n(30.379441, -97.751594)"
50,shots fired,"1919 Burton Dr\n(30.233907, -97.731631)"
51,domestic disturbance,"6301 Berkman Dr\n(30.316889, -97.690853)"
52,burglar alarm,"4714 S Congress Ave\n(30.214181, -97.769479)"
53,domestic disturbance,"12501 Tech Ridge Blvd\n(30.398698, -97.661704)"
54,suspicious person,"12000 block Natures Bnd\n(30.391489, -97.667084)"

In [39]:
new = df_shoot["Location 1"].str.split("\(", n = 1, expand = True) 
new

                                                   0                        1
0                                      8206 Pax Dr\n   30.244609, -97.888612)
1                                     715 E 8th St\n  48.192789, -114.299949)
2                            1609 Cripple Creek Dr\n   30.379773, -97.704626)
3                                 7600 MANCHACA RD\n     30.1955, -97.810196)
4                                   600 TRINITY ST\n   29.881245, -97.667536)
5                            9218 Balcones Club Dr\n   30.443284, -97.787553)
6                              3630 S Congress Ave\n   26.489341, -80.089825)
7                               300 block E 6th St\n   38.848634, -91.944226)
8                                   3300 E 12th St\n   40.178357, -85.348554)
9                               120 W Slaughter Ln\n   30.167208, -97.788916)
10                           3708 Aspen Creek Pkwy\n   30.181796, -97.856066)
11                           10607 Golden Quail Dr\n    30.379781, -97.70205)
12                               9400 N Lamar Blvd\n   30.363177, -97.696992)
13                         801 E William Cannon Dr\n    30.19096, -97.771937)
14                        7800 E Ben White Blvd WB\n   30.219623, -97.689696)
15                         744 W William Cannon Dr\n   30.197953, -97.789496)
16                      11300 block LONG WINTER DR\n    37.49396, -92.294899)
17                              810 E Slaughter Ln\n    30.159946, -97.77643)
18                            7800 N IH 35 Svrd SB\n    29.56345, -98.340468)
19                            700 San Jacinto Blvd\n   30.269158, -97.739649)
20                              6321 PARLIAMENT DR\n    30.28687, -97.658896)
21  12320 Tomanet Trl / 12331 N Mopac Expy Svrd NB\n    30.41496, -97.703314)
22                              6409 Springdale Rd\n   30.307201, -97.669664)
23                               1100 Marks Circle\n   30.268608, -97.691009)
24                              800 Block E 8th St\n   40.868762, -97.583783)
25                      11815 Johnny Weismuller Ln\n   30.151215, -97.843473)
26                       6600 S MoPac Expy Svrd SB\n   30.221231, -97.836546)
27                                5007 Lynnwood St\n   30.322115, -97.740477)
28                               10617 Lanshire Dr\n   30.384132, -97.708018)
29                                  11512 OLSON DR\n   30.445259, -97.805086)
30                                 13006 Campos Dr\n   30.438023, -97.740493)
31                                6505 Shirley Ave\n    30.33259, -97.720879)
32                                    2900 Cole St\n     30.2877, -97.725141)
33                              1515 Wickersham Ln\n   30.235461, -97.718944)
34                         5200 Block Overbrook Dr\n   30.298349, -97.684711)
35                         4201 Monterey Oaks Blvd\n    30.228925, -97.83392)
36                                    508 West Ave\n   30.298878, -82.978832)
37                       6855 E US 290 Hwy SVRD EB\n   30.321071, -97.687437)
38                          9416 Neils Thompson Dr\n   30.382402, -97.733069)
39                  7112 Ed Bluestein Blvd SVRD SB\n    30.312738, -97.66281)
40                                 9400 Claxton Dr\n   30.246406, -97.910421)
41                              6409 Springdale Rd\n   30.307201, -97.669664)
42                                  1002 Morrow St\n   30.345194, -97.717559)
43                             7201 Wood Hollow Dr\n   30.355057, -97.752106)
44                                   13712 Maye Pl\n   30.426237, -97.673119)
45                            9811 N IH 35 SVRD NB\n   30.362494, -97.684934)
46                            2915 S IH 35 Svrd NB\n    30.227091, -97.74466)
47                                 6603 Berkman Dr\n   30.319315, -97.689358)
48                                   706 Valdez St\n   30.234584, -97.691949)
49                            4022 Greenhill Place\n   30.379441, -97.751594)
50                                  1919 Burton Dr\n   30.233907, -97.731631)
51                                 6301 Berkman Dr\n   30.316889, -97.690853)
52                             4714 S Congress Ave\n   30.214181, -97.769479)
53                           12501 Tech Ridge Blvd\n   30.398698, -97.661704)
54                         12000 block Natures Bnd\n   30.391489, -97.667084)

In [40]:
del new[0]
new

                          1
0    30.244609, -97.888612)
1   48.192789, -114.299949)
2    30.379773, -97.704626)
3      30.1955, -97.810196)
4    29.881245, -97.667536)
5    30.443284, -97.787553)
6    26.489341, -80.089825)
7    38.848634, -91.944226)
8    40.178357, -85.348554)
9    30.167208, -97.788916)
10   30.181796, -97.856066)
11    30.379781, -97.70205)
12   30.363177, -97.696992)
13    30.19096, -97.771937)
14   30.219623, -97.689696)
15   30.197953, -97.789496)
16    37.49396, -92.294899)
17    30.159946, -97.77643)
18    29.56345, -98.340468)
19   30.269158, -97.739649)
20    30.28687, -97.658896)
21    30.41496, -97.703314)
22   30.307201, -97.669664)
23   30.268608, -97.691009)
24   40.868762, -97.583783)
25   30.151215, -97.843473)
26   30.221231, -97.836546)
27   30.322115, -97.740477)
28   30.384132, -97.708018)
29   30.445259, -97.805086)
30   30.438023, -97.740493)
31    30.33259, -97.720879)
32     30.2877, -97.725141)
33   30.235461, -97.718944)
34   30.298349, -97.684711)
35    30.228925, -97.83392)
36   30.298878, -82.978832)
37   30.321071, -97.687437)
38   30.382402, -97.733069)
39    30.312738, -97.66281)
40   30.246406, -97.910421)
41   30.307201, -97.669664)
42   30.345194, -97.717559)
43   30.355057, -97.752106)
44   30.426237, -97.673119)
45   30.362494, -97.684934)
46    30.227091, -97.74466)
47   30.319315, -97.689358)
48   30.234584, -97.691949)
49   30.379441, -97.751594)
50   30.233907, -97.731631)
51   30.316889, -97.690853)
52   30.214181, -97.769479)
53   30.398698, -97.661704)
54   30.391489, -97.667084)

In [42]:
new1 = new[1].str.split(" ", n = 1, expand = True) 
new1

             0             1
0   30.244609,   -97.888612)
1   48.192789,  -114.299949)
2   30.379773,   -97.704626)
3     30.1955,   -97.810196)
4   29.881245,   -97.667536)
5   30.443284,   -97.787553)
6   26.489341,   -80.089825)
7   38.848634,   -91.944226)
8   40.178357,   -85.348554)
9   30.167208,   -97.788916)
10  30.181796,   -97.856066)
11  30.379781,    -97.70205)
12  30.363177,   -97.696992)
13   30.19096,   -97.771937)
14  30.219623,   -97.689696)
15  30.197953,   -97.789496)
16   37.49396,   -92.294899)
17  30.159946,    -97.77643)
18   29.56345,   -98.340468)
19  30.269158,   -97.739649)
20   30.28687,   -97.658896)
21   30.41496,   -97.703314)
22  30.307201,   -97.669664)
23  30.268608,   -97.691009)
24  40.868762,   -97.583783)
25  30.151215,   -97.843473)
26  30.221231,   -97.836546)
27  30.322115,   -97.740477)
28  30.384132,   -97.708018)
29  30.445259,   -97.805086)
30  30.438023,   -97.740493)
31   30.33259,   -97.720879)
32    30.2877,   -97.725141)
33  30.235461,   -97.718944)
34  30.298349,   -97.684711)
35  30.228925,    -97.83392)
36  30.298878,   -82.978832)
37  30.321071,   -97.687437)
38  30.382402,   -97.733069)
39  30.312738,    -97.66281)
40  30.246406,   -97.910421)
41  30.307201,   -97.669664)
42  30.345194,   -97.717559)
43  30.355057,   -97.752106)
44  30.426237,   -97.673119)
45  30.362494,   -97.684934)
46  30.227091,    -97.74466)
47  30.319315,   -97.689358)
48  30.234584,   -97.691949)
49  30.379441,   -97.751594)
50  30.233907,   -97.731631)
51  30.316889,   -97.690853)
52  30.214181,   -97.769479)
53  30.398698,   -97.661704)
54  30.391489,   -97.667084)

In [43]:
df_shoot["Lat"] = new1[0]
df_shoot["Long"] = new1[1]

df_shoot

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Call Type Categories,Location 1,Lat,Long
0,shots fired,"8206 Pax Dr\n(30.244609, -97.888612)","30.244609,",-97.888612)
1,shots fired,"715 E 8th St\n(48.192789, -114.299949)","48.192789,",-114.299949)
2,shots fired,"1609 Cripple Creek Dr\n(30.379773, -97.704626)","30.379773,",-97.704626)
3,other - nature unknown,"7600 MANCHACA RD\n(30.1955, -97.810196)","30.1955,",-97.810196)
4,shots fired,"600 TRINITY ST\n(29.881245, -97.667536)","29.881245,",-97.667536)
5,warrant,"9218 Balcones Club Dr\n(30.443284, -97.787553)","30.443284,",-97.787553)
6,robbery,"3630 S Congress Ave\n(26.489341, -80.089825)","26.489341,",-80.089825)
7,disturbance,"300 block E 6th St\n(38.848634, -91.944226)","38.848634,",-91.944226)
8,traffic stop,"3300 E 12th St\n(40.178357, -85.348554)","40.178357,",-85.348554)
9,domestic disturbance,"120 W Slaughter Ln\n(30.167208, -97.788916)","30.167208,",-97.788916)
10,stolen vehicle,"3708 Aspen Creek Pkwy\n(30.181796, -97.856066)","30.181796,",-97.856066)
11,suicidal subject,"10607 Golden Quail Dr\n(30.379781, -97.70205)","30.379781,",-97.70205)
12,other - flagged down by victim of an LTS,"9400 N Lamar Blvd\n(30.363177, -97.696992)","30.363177,",-97.696992)
13,burglar alarm,"801 E William Cannon Dr\n(30.19096, -97.771937)","30.19096,",-97.771937)
14,domestic disturbance,"7800 E Ben White Blvd WB\n(30.219623, -97.689696)","30.219623,",-97.689696)
15,check welfare,"744 W William Cannon Dr\n(30.197953, -97.789496)","30.197953,",-97.789496)
16,disturbance,"11300 block LONG WINTER DR\n(37.49396, -92.294...","37.49396,",-92.294899)
17,disturbance,"810 E Slaughter Ln\n(30.159946, -97.77643)","30.159946,",-97.77643)
18,other - narcotics,"7800 N IH 35 Svrd SB\n(29.56345, -98.340468)","29.56345,",-98.340468)
19,shots fired,"700 San Jacinto Blvd\n(30.269158, -97.739649)","30.269158,",-97.739649)
20,disturbance,"6321 PARLIAMENT DR\n(30.28687, -97.658896)","30.28687,",-97.658896)
21,disturbance,12320 Tomanet Trl / 12331 N Mopac Expy Svrd NB...,"30.41496,",-97.703314)
22,suspicious person,"6409 Springdale Rd\n(30.307201, -97.669664)","30.307201,",-97.669664)
23,traffic stop,"1100 Marks Circle\n(30.268608, -97.691009)","30.268608,",-97.691009)
24,suspicious person,"800 Block E 8th St\n(40.868762, -97.583783)","40.868762,",-97.583783)
25,domestic disturbance,"11815 Johnny Weismuller Ln\n(30.151215, -97.84...","30.151215,",-97.843473)
26,disturbance,"6600 S MoPac Expy Svrd SB\n(30.221231, -97.836...","30.221231,",-97.836546)
27,other - stabbing,"5007 Lynnwood St\n(30.322115, -97.740477)","30.322115,",-97.740477)
28,shots fired,"10617 Lanshire Dr\n(30.384132, -97.708018)","30.384132,",-97.708018)
29,disturbance,"11512 OLSON DR\n(30.445259, -97.805086)","30.445259,",-97.805086)
30,traffic stop,"13006 Campos Dr\n(30.438023, -97.740493)","30.438023,",-97.740493)
31,suicidal subject,"6505 Shirley Ave\n(30.33259, -97.720879)","30.33259,",-97.720879)
32,check welfare,"2900 Cole St\n(30.2877, -97.725141)","30.2877,",-97.725141)
33,traffic stop,"1515 Wickersham Ln\n(30.235461, -97.718944)","30.235461,",-97.718944)
34,traffic stop,"5200 Block Overbrook Dr\n(30.298349, -97.684711)","30.298349,",-97.684711)
35,suspicious person,"4201 Monterey Oaks Blvd\n(30.228925, -97.83392)","30.228925,",-97.83392)
36,disturbance,"508 West Ave\n(30.298878, -82.978832)","30.298878,",-82.978832)
37,shots fired,"6855 E US 290 Hwy SVRD EB\n(30.321071, -97.687...","30.321071,",-97.687437)
38,burglar alarm,"9416 Neils Thompson Dr\n(30.382402, -97.733069)","30.382402,",-97.733069)
39,robbery,"7112 Ed Bluestein Blvd SVRD SB\n(30.312738, -9...","30.312738,",-97.66281)
40,suspicious person,"9400 Claxton Dr\n(30.246406, -97.910421)","30.246406,",-97.910421)
41,other - robbery suspect vehicle,"6409 Springdale Rd\n(30.307201, -97.669664)","30.307201,",-97.669664)
42,warrant,"1002 Morrow St\n(30.345194, -97.717559)","30.345194,",-97.717559)
43,check welfare,"7201 Wood Hollow Dr\n(30.355057, -97.752106)","30.355057,",-97.752106)
44,warrant,"13712 Maye Pl\n(30.426237, -97.673119)","30.426237,",-97.673119)
45,other - aggravated assault,"9811 N IH 35 SVRD NB\n(30.362494, -97.684934)","30.362494,",-97.684934)
46,stolen vehicle,"2915 S IH 35 Svrd NB\n(30.227091, -97.74466)","30.227091,",-97.74466)
47,disturbance,"6603 Berkman Dr\n(30.319315, -97.689358)","30.319315,",-97.689358)
48,suicidal subject,"706 Valdez St\n(30.234584, -97.691949)","30.234584,",-97.691949)
49,disturbance,"4022 Greenhill Place\n(30.379441, -97.751594)","30.379441,",-97.751594)
50,shots fired,"1919 Burton Dr\n(30.233907, -97.731631)","30.233907,",-97.731631)
51,domestic disturbance,"6301 Berkman Dr\n(30.316889, -97.690853)","30.316889,",-97.690853)
52,burglar alarm,"4714 S Congress Ave\n(30.214181, -97.769479)","30.214181,",-97.769479)
53,domestic disturbance,"12501 Tech Ridge Blvd\n(30.398698, -97.661704)","30.398698,",-97.661704)
54,suspicious person,"12000 block Natures Bnd\n(30.391489, -97.667084)","30.391489,",-97.667084)

In [44]:
del df_shoot['Location 1']
df_shoot.head()

     Call Type Categories         Lat          Long
0             shots fired  30.244609,   -97.888612)
1             shots fired  48.192789,  -114.299949)
2             shots fired  30.379773,   -97.704626)
3  other - nature unknown    30.1955,   -97.810196)
4             shots fired  29.881245,   -97.667536)

In [45]:
df_shoot['Lat'] = df_shoot['Lat'].str[:-1]
df_shoot['Long'] = df_shoot['Long'].str[:-1]
df_shoot

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                        Call Type Categories        Lat         Long
0                                shots fired  30.244609   -97.888612
1                                shots fired  48.192789  -114.299949
2                                shots fired  30.379773   -97.704626
3                     other - nature unknown    30.1955   -97.810196
4                                shots fired  29.881245   -97.667536
5                                    warrant  30.443284   -97.787553
6                                    robbery  26.489341   -80.089825
7                                disturbance  38.848634   -91.944226
8                               traffic stop  40.178357   -85.348554
9                       domestic disturbance  30.167208   -97.788916
10                            stolen vehicle  30.181796   -97.856066
11                          suicidal subject  30.379781    -97.70205
12  other - flagged down by victim of an LTS  30.363177   -97.696992
13                             burglar alarm   30.19096   -97.771937
14                      domestic disturbance  30.219623   -97.689696
15                             check welfare  30.197953   -97.789496
16                               disturbance   37.49396   -92.294899
17                               disturbance  30.159946    -97.77643
18                         other - narcotics   29.56345   -98.340468
19                               shots fired  30.269158   -97.739649
20                               disturbance   30.28687   -97.658896
21                               disturbance   30.41496   -97.703314
22                         suspicious person  30.307201   -97.669664
23                              traffic stop  30.268608   -97.691009
24                         suspicious person  40.868762   -97.583783
25                      domestic disturbance  30.151215   -97.843473
26                               disturbance  30.221231   -97.836546
27                          other - stabbing  30.322115   -97.740477
28                               shots fired  30.384132   -97.708018
29                               disturbance  30.445259   -97.805086
30                              traffic stop  30.438023   -97.740493
31                          suicidal subject   30.33259   -97.720879
32                             check welfare    30.2877   -97.725141
33                              traffic stop  30.235461   -97.718944
34                              traffic stop  30.298349   -97.684711
35                         suspicious person  30.228925    -97.83392
36                               disturbance  30.298878   -82.978832
37                               shots fired  30.321071   -97.687437
38                             burglar alarm  30.382402   -97.733069
39                                   robbery  30.312738    -97.66281
40                         suspicious person  30.246406   -97.910421
41           other - robbery suspect vehicle  30.307201   -97.669664
42                                   warrant  30.345194   -97.717559
43                             check welfare  30.355057   -97.752106
44                                   warrant  30.426237   -97.673119
45                other - aggravated assault  30.362494   -97.684934
46                            stolen vehicle  30.227091    -97.74466
47                               disturbance  30.319315   -97.689358
48                          suicidal subject  30.234584   -97.691949
49                               disturbance  30.379441   -97.751594
50                               shots fired  30.233907   -97.731631
51                      domestic disturbance  30.316889   -97.690853
52                             burglar alarm  30.214181   -97.769479
53                      domestic disturbance  30.398698   -97.661704
54                         suspicious person  30.391489   -97.667084

In [48]:
df_shoot.columns = [['Name','Lat','Long']]
df_shoot.head()

                     Name        Lat         Long
0             shots fired  30.244609   -97.888612
1             shots fired  48.192789  -114.299949
2             shots fired  30.379773   -97.704626
3  other - nature unknown    30.1955   -97.810196
4             shots fired  29.881245   -97.667536

In [63]:
df_shoot['Category'] = 'Shooting'
df_shoot.head()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                     Name        Lat         Long  Category
0             shots fired  30.244609   -97.888612  Shooting
1             shots fired  48.192789  -114.299949  Shooting
2             shots fired  30.379773   -97.704626  Shooting
3  other - nature unknown    30.1955   -97.810196  Shooting
4             shots fired  29.881245   -97.667536  Shooting

In [49]:
df_elec = pd.read_csv('Plug-In_EVerywhere_Charging_Station_Network.csv') 
df_elec

,Station Name,Address 1,Address 2,City,State,Postal Code,No. of Ports,Pricing Policy,Usage Access,Category,Subcategory,Port 1: Connector Type,Voltage (V),Port 2: Connector Type,New Georeferenced Column,Pricing,Power Select
0,CATHERINE / CATHERINE 1,300 Barton Springs Rd,NaN,Austin,Texas,78704,2,$4.17/month PIE members $2/hr Non-Members,Multi-family residential,Multifamily Commercial,Apartment,J1772,240V,J1772,"(30.259096, -97.747775)",$4.17/month PIE members $2/hr Non-Members,40A
1,AUSTIN HQ / STATION 1,4200 Smith School Dr,NaN,Austin,Texas,78744,2,$4.17/month PIE members $2/hr Non-Members,Commercial with unrestricted access,Workplace,General,J1772,240V,J1772,"(30.192647, -97.714329)",$4.17/month PIE members $2/hr Non-Members,40A
2,SCHOOL / AKINS1,10701 S 1st St.,NaN,Austin,Texas,78748,2,$4.17/month PIE members $2/hr Non-Members,"Public (Municipal, as in library, street, etc)",Education,High School / Other,J1772,240V,J1772,"(30.147634, -97.801294)",$4.17/month PIE members $2/hr Non-Members,40A
3,MONOGRAM / HANDICAP,615 W 7th St,NaN,Austin,Texas,78701,1,$4.17/month PIE members $2/hr Non-Members,Multi-family residential,Multifamily Commercial,Apartment,J1772,--,--,"(30.270571, -97.748993)",$4.17/month PIE members $2/hr Non-Members,40A
4,FLATIRON DOMAIN / FLATIRON DOM 2,10727 domain dr,NaN,Austin,Texas,78758,2,$4.17/month PIE members $2/hr Non-Members,Multi-family residential,Multifamily Commercial,Apartment,J1772,240V,J1772,"(30.392852, -97.723729)",$4.17/month PIE members $2/hr Non-Members,40A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,AISD PAC / AISD PAC #5,1301-1603 E 51st St,NaN,Austin,Texas,78723,2,$4.17/month PIE members $2/hr Non-Members,Commercial with unrestricted access,Education,High School / Other,J1772,240V,J1772,"(30.305204, -97.702108)",$4.17/month PIE members $2/hr Non-Members,40A
463,HPI 3700 / EV 6,4339 N Capital of Texas Hwy,NaN,Austin,Texas,78746,1,$4.17/month PIE members $2/hr Non-Members,Commercial with unrestricted access,Workplace,General,J1772,--,--,"(30.336616, -97.8076)",$4.17/month PIE members $2/hr Non-Members,40A
464,PIE AE / PALMER STATION3,736-820 Barton Springs Rd,NaN,Austin,Texas,78704,2,$4.17/month PIE members $2/hr Non-Members,Commercial with unrestricted access,Parking,Commercial,J1772,240V,J1772,"(30.259236, -97.751809)",$4.17/month PIE members $2/hr Non-Members,40A
465,ROSCOE PROPERTI / TRIO MAIN,2413-2433 S Pleasant Valley Rd,NaN,Austin,Texas,78741,2,$4.17/month PIE members $2/hr Non-Members,Multi-family residential,Multifamily Commercial,Apartment,J1772,240V,J1772,"(30.228786, -97.726326)",$4.17/month PIE members $2/hr Non-Members,40A
466,DSMCUT / EVSE01 FLOOR L7,501-573 E 15th St,NaN,Austin,Texas,78701,2,$4.17/month PIE members $2/hr Non-Members,Commercial with unrestricted access,Healthcare,Hospital / Treatment Center,J1772,240V,J1772,"(30.275261, -97.73458)",$4.17/month PIE members $2/hr Non-Members,40A

In [50]:
df_elec = df_elec[['Station Name','New Georeferenced Column']]

df_elec.head()

                       Station Name New Georeferenced Column
0           CATHERINE / CATHERINE 1  (30.259096, -97.747775)
1             AUSTIN HQ / STATION 1  (30.192647, -97.714329)
2                   SCHOOL / AKINS1  (30.147634, -97.801294)
3               MONOGRAM / HANDICAP  (30.270571, -97.748993)
4  FLATIRON DOMAIN / FLATIRON DOM 2  (30.392852, -97.723729)

In [51]:
new = df_elec["New Georeferenced Column"].str.split(" ", n = 1, expand = True) 
new.head()

             0            1
0  (30.259096,  -97.747775)
1  (30.192647,  -97.714329)
2  (30.147634,  -97.801294)
3  (30.270571,  -97.748993)
4  (30.392852,  -97.723729)

In [52]:
new[0] = new[0].str[1:-1]
new[1] = new[1].str[:-1]

new.head()

           0           1
0  30.259096  -97.747775
1  30.192647  -97.714329
2  30.147634  -97.801294
3  30.270571  -97.748993
4  30.392852  -97.723729

In [54]:
del df_elec["New Georeferenced Column"]

df_elec['Lat'] = new[0]
df_elec['Long'] = new[1]

df_elec.head()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

                       Station Name        Lat        Long
0           CATHERINE / CATHERINE 1  30.259096  -97.747775
1             AUSTIN HQ / STATION 1  30.192647  -97.714329
2                   SCHOOL / AKINS1  30.147634  -97.801294
3               MONOGRAM / HANDICAP  30.270571  -97.748993
4  FLATIRON DOMAIN / FLATIRON DOM 2  30.392852  -97.723729

In [55]:
df_elec.columns = ['Name','Lat','Long']

df_elec.head()

                               Name        Lat        Long
0           CATHERINE / CATHERINE 1  30.259096  -97.747775
1             AUSTIN HQ / STATION 1  30.192647  -97.714329
2                   SCHOOL / AKINS1  30.147634  -97.801294
3               MONOGRAM / HANDICAP  30.270571  -97.748993
4  FLATIRON DOMAIN / FLATIRON DOM 2  30.392852  -97.723729

In [62]:
df_elec['Category'] = 'ElecCarCharging'
df_elec.head()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                               Name        Lat        Long         Category
0           CATHERINE / CATHERINE 1  30.259096  -97.747775  ElecCarCharging
1             AUSTIN HQ / STATION 1  30.192647  -97.714329  ElecCarCharging
2                   SCHOOL / AKINS1  30.147634  -97.801294  ElecCarCharging
3               MONOGRAM / HANDICAP  30.270571  -97.748993  ElecCarCharging
4  FLATIRON DOMAIN / FLATIRON DOM 2  30.392852  -97.723729  ElecCarCharging

In [56]:
df_house = pd.read_csv('Affordable_Housing_Listing.csv') 
df_house.head()

,Project Name,Address,Zip Code,Total Units,Total Affordable Units,Unit Type,Housing Type,Status,1 Person Household,2 Person Household,3 Person Household,4 Person Household,5 Person Household,Property Management Company,Phone,Website,Longitude,Latitude.,Location
0,Lyons Gardens,2720 Lyons Road,78702,54,53,Multifamily,Residential Housing,Project Completed,30100,24400,38700,43000,46450,Alpha Barnes Real Estate Services,512-236-1781,http://www.lyonsgardens.com/,-97.709189,30.264579,"(30.2645793410541, -97.7091893422922)"
1,Rio West Student Living,2704 Rio Grande Street,78705,76,8,Multifamily,Student Housing,Project Completed,48200,55050,61950,68800,74350,Coastal Ridge Real Estate,512-236-1903,https://rioweststudentliving.com/,-97.744544,30.292961,"(30.2929610272008, -97.7445438848349)"
2,Live Oak Trails,8500 US Highway 71 W,78735,58,58,Multifamily,Residential Housing,Project Completed,30100,24400,38700,43000,46450,Foundation Communities,512-610-2240,http://foundcom.org/housing/our-austin-communi...,-97.890082,30.248559,"(30.2485593811554, -97.8900821644269)"
3,The Residences at The Domain,11400 Domain Drive,78758,390,39,Multifamily,Residential Housing,Project Completed,39150,44700,50300,55900,60350,UDR,512-237-7838,https://www.udr.com/austin-apartments/north-bu...,-97.724930,30.400623,"(30.400623, -97.72493)"
4,Guadalupe Saldana - Duplex,1220 Paul Theresa Saldana Street,78702,2,2,Duplex,Residential Housing,Project Completed,30100,24400,38700,43000,46450,Guadalupe Neighborhood Development Corporation,512-479-6275,http://www.guadalupendc.org/,-97.702958,30.269889,"(30.269889, -97.702958)"

In [57]:
df_house = df_house[['Project Name', 'Longitude','Latitude.']]
df_house.head()

                   Project Name  Longitude  Latitude.
0                 Lyons Gardens -97.709189  30.264579
1       Rio West Student Living -97.744544  30.292961
2               Live Oak Trails -97.890082  30.248559
3  The Residences at The Domain -97.724930  30.400623
4    Guadalupe Saldana - Duplex -97.702958  30.269889

In [59]:
df_house = df_house[['Project Name', 'Latitude.', 'Longitude']]
df_house.head()

                   Project Name  Latitude.  Longitude
0                 Lyons Gardens  30.264579 -97.709189
1       Rio West Student Living  30.292961 -97.744544
2               Live Oak Trails  30.248559 -97.890082
3  The Residences at The Domain  30.400623 -97.724930
4    Guadalupe Saldana - Duplex  30.269889 -97.702958

In [60]:
df_house.columns = ['Name', 'Lat', 'Long']
df_house.head()

                           Name        Lat       Long
0                 Lyons Gardens  30.264579 -97.709189
1       Rio West Student Living  30.292961 -97.744544
2               Live Oak Trails  30.248559 -97.890082
3  The Residences at The Domain  30.400623 -97.724930
4    Guadalupe Saldana - Duplex  30.269889 -97.702958

In [61]:
df_house['Category'] = 'AffordableHousing'
df_house.head()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                           Name        Lat       Long           Category
0                 Lyons Gardens  30.264579 -97.709189  AffordableHousing
1       Rio West Student Living  30.292961 -97.744544  AffordableHousing
2               Live Oak Trails  30.248559 -97.890082  AffordableHousing
3  The Residences at The Domain  30.400623 -97.724930  AffordableHousing
4    Guadalupe Saldana - Duplex  30.269889 -97.702958  AffordableHousing

In [80]:
df_markers = pd.concat([df_golf, df_labs], ignore_index=True)
df_markers

                           Name        Lat        Long     Category
0   Lions Municipal Golf Course    30.2916    -97.7743   GolfCourse
1     Joe Balander Short Course    30.1882    -97.7325   GolfCourse
2   Morris Williams Golf Course    30.2901    -97.6942   GolfCourse
3         Roy Kizer Golf Course    30.1882    -97.7325   GolfCourse
4           Hancock Golf Course    30.2998    -97.7226   GolfCourse
5        Jimmy Clay Golf Course    30.1882    -97.7325   GolfCourse
6                          ARCH  30.267652  -97.737726  ComputerLab
7                Howson Library  30.298139  -97.767313  ComputerLab
8            Old Quarry Library  30.353257  -97.755751  ComputerLab
9     Spicewood Springs Library  30.433288  -97.772786  ComputerLab
10         Windsor Park Library  30.311258  -97.690559  ComputerLab
11               Carver Library   30.26995  -97.724523  ComputerLab
12  Little Walnut Creek Library  30.363634  -97.698231  ComputerLab
13        North Village Library  30.362014  -97.729717  ComputerLab
14            Southeast Library  30.187926  -97.742224  ComputerLab
15              Central Library  30.265509  -97.751941  ComputerLab
16            Twin Oaks Library  30.248884  -97.761726  ComputerLab
17                 Ruiz Library  30.230228  -97.706314  ComputerLab
18        Manchaca Road Library  30.216327  -97.796899  ComputerLab
19               Cepeda Library  30.259785  -97.709632  ComputerLab
20     University Hills Library  30.308952  -97.666211  ComputerLab
21             Terrazas Library  30.260114  -97.733214  ComputerLab
22        Pleasant Hill Library  30.192555  -97.777026  ComputerLab
23              Milwood Library  30.423153  -97.714651  ComputerLab
24      Willie Mae Kirk Library  30.273232   -97.69999  ComputerLab
25               Dewitty Center   30.27021    -97.7159  ComputerLab
26             St. John Library  30.331949  -97.693032  ComputerLab

In [82]:
df_markers = df_markers.append(df_elec, ignore_index=True)
df_markers

                            Name        Lat        Long         Category
0    Lions Municipal Golf Course    30.2916    -97.7743       GolfCourse
1      Joe Balander Short Course    30.1882    -97.7325       GolfCourse
2    Morris Williams Golf Course    30.2901    -97.6942       GolfCourse
3          Roy Kizer Golf Course    30.1882    -97.7325       GolfCourse
4            Hancock Golf Course    30.2998    -97.7226       GolfCourse
..                           ...        ...         ...              ...
489       AISD PAC / AISD PAC #5  30.305204  -97.702108  ElecCarCharging
490              HPI 3700 / EV 6  30.336616    -97.8076  ElecCarCharging
491     PIE AE / PALMER STATION3  30.259236  -97.751809  ElecCarCharging
492  ROSCOE PROPERTI / TRIO MAIN  30.228786  -97.726326  ElecCarCharging
493     DSMCUT / EVSE01 FLOOR L7  30.275261   -97.73458  ElecCarCharging

[494 rows x 4 columns]

In [83]:
df_markers = df_markers.append(df_house, ignore_index=True)
df_markers

                            Name      Lat     Long           Category
0    Lions Municipal Golf Course  30.2916 -97.7743         GolfCourse
1      Joe Balander Short Course  30.1882 -97.7325         GolfCourse
2    Morris Williams Golf Course  30.2901 -97.6942         GolfCourse
3          Roy Kizer Golf Course  30.1882 -97.7325         GolfCourse
4            Hancock Golf Course  30.2998 -97.7226         GolfCourse
..                           ...      ...      ...                ...
804             Heritage Heights  30.2657 -97.7233  AffordableHousing
805        Villages at Fiskville  30.3644 -97.6813  AffordableHousing
806     Elan Parkside Apartments  30.3269  -97.716  AffordableHousing
807  SafePlace 14 Unit Expansion  30.2314 -97.7058  AffordableHousing
808             Lakeline Station  30.4763 -97.7803  AffordableHousing

[809 rows x 4 columns]

In [85]:
df_house.columns

Index(['Name', 'Lat', 'Long', 'Category'], dtype='object')

In [86]:
df_markers.columns

Index(['Name', 'Lat', 'Long', 'Category'], dtype='object')

In [92]:
df_shoot.columns = ['Name', 'Lat', 'Long', 'Category']
df_shoot.columns[:]

Index(['Name', 'Lat', 'Long', 'Category'], dtype='object')

In [90]:
df_elec.columns[:]

Index(['Name', 'Lat', 'Long', 'Category'], dtype='object')

In [93]:
df_markers = df_markers.append(df_shoot, ignore_index=True)
df_markers

                            Name        Lat        Long    Category
0    Lions Municipal Golf Course    30.2916    -97.7743  GolfCourse
1      Joe Balander Short Course    30.1882    -97.7325  GolfCourse
2    Morris Williams Golf Course    30.2901    -97.6942  GolfCourse
3          Roy Kizer Golf Course    30.1882    -97.7325  GolfCourse
4            Hancock Golf Course    30.2998    -97.7226  GolfCourse
..                           ...        ...         ...         ...
859                  shots fired  30.233907  -97.731631    Shooting
860         domestic disturbance  30.316889  -97.690853    Shooting
861                burglar alarm  30.214181  -97.769479    Shooting
862         domestic disturbance  30.398698  -97.661704    Shooting
863            suspicious person  30.391489  -97.667084    Shooting

[864 rows x 4 columns]

In [94]:
df_markers.to_csv('markers.csv', index=False)